const verPropiedadesNavegador = ()=>{
	console.log("AppCodeName: ",navigator.appCodeName);
	console.log("");
	console.log("AppName: ",navigator.appName);
	console.log("");
	console.log("AppVersion: ",navigator.appVersion);
	console.log("");
	console.log("Connection: ",navigator.connection);
	console.log("");
	console.log("Geolocation: ",navigator.geolocation);
	console.log("");
	console.log("HardwareCocurrency: ",navigator.hardwareConcurrency);
	console.log("");
	console.log("Language: ",navigator.language);
	console.log("");
	console.log("Lenguages: ",navigator.languages);
	console.log("");
	console.log("MimeTypes: ",navigator.mimeTypes);
	console.log("");
	console.log("OnLine: ",navigator.onLine);
	console.log("");
	console.log("UserAgent: ",navigator.userAgent);
	console.log("");
	console.log("CookieEnabled: ",navigator.cookieEnabled);
	console.log("");
	console.log("Permissions: ",navigator.permissions);
	console.log("");
	console.log("Plataform: ",navigator.platform);
	console.log("");
	console.log("Plugins: ",navigator.plugins);
	console.log("");
	console.log("Product: ",navigator.product);
	console.log("");
}